services:
  - type: web
    name: rca-risk-assessment
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    plan: free
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rca-database
          property: connectionString
databases:
  - name: rca-database
    databaseName: rca_db
    user: rca_user
    plan: free
